import PIsNPOrNot
import ResearchNext
import ResearchThird
import ResearchFourth
import ResearchAgenda
import ResearchFifth
import ResearchSixth
import ResearchSeventh
import ResearchEighth
import ResearchNinth
import ResearchTenth
import ResearchEleventh
import ResearchTwelfth
import ResearchThirteenth
import ResearchFourteenth
import ResearchFifteenth
import ResearchSixteenth
import ResearchSeventeenth
import ResearchEighteenth
import ResearchNineteenth
import ResearchTwentieth
import ResearchTwentyFirst
import ResearchTwentySecond
import ResearchTwentyThird
import ResearchTwentyFourth
import ResearchTwentyFifth
import ResearchTwentySixth
import ResearchTwentySeventh
import ResearchTwentyEighth
import ResearchTwentyNinth
import ResearchThirtieth
import ResearchThirtyFirst
import ResearchThirtySecond
import ResearchThirtyThird
import ResearchThirtyFourth
import ResearchThirtyFifth
import ResearchThirtySixth
import ResearchThirtySeventh
import ResearchThirtyEighth
import ResearchThirtyNinth
import ResearchFortieth
import CNFCore

-- Original residual and decomposition core
#print axioms PIsNPOrNot.A06_SeparatorDP.separator_factorization
#print axioms PIsNPOrNot.A15_ResidualAutomaton.dpAccept_correct
#print axioms PIsNPOrNot.Synthesis_ResidualCompression.ResidualModel.decide_correct

-- Lower bounds and structural barriers
#print axioms PIsNPOrNot.ResearchNext.A17_EqualityRowLowerBound.bit_state_lower_bound
#print axioms PIsNPOrNot.ResearchNext.A18_DistinguishableResiduals.state_card_lower_bound
#print axioms PIsNPOrNot.ResearchNext.A19_HittingSetBarrier.bit_hitting_set_card
#print axioms PIsNPOrNot.ResearchNext.A23_BlackBoxSpike.existential_answers_differ

-- CNF restriction and certified dispatch
#print axioms PIsNPOrNot.CNFCore.evalCNF_restrict
#print axioms PIsNPOrNot.CNFCore.branch_preserves_satisfying_assignments
#print axioms PIsNPOrNot.ResearchNext.A31_CertifiedDispatch.dispatch_correct
#print axioms PIsNPOrNot.ResearchNext.A32_CertifiedPortfolio.chosen_result_sound

-- Approaches 33-47
#print axioms PIsNPOrNot.ResearchThird.A33_CertifiedCoverage.firstAnswer_total
#print axioms PIsNPOrNot.ResearchThird.A41_EntailedLearning.add_entailed_preserves_sat
#print axioms PIsNPOrNot.ResearchThird.A42_ResolutionStep.resolution_sound
#print axioms PIsNPOrNot.ResearchThird.A46_DecompositionTree.solve_true_iff_leaf
#print axioms PIsNPOrNot.ResearchThird.A47_UniversalHybrid.hybrid_correct

-- Approaches 48-55
#print axioms PIsNPOrNot.ResearchFourth.A48_XorEncoding.xor3CNF_correct
#print axioms PIsNPOrNot.ResearchFourth.A49_RowAddition.replace_second_row
#print axioms PIsNPOrNot.ResearchFourth.A52_AffineDispatch.dispatch_correct
#print axioms PIsNPOrNot.ResearchFourth.A55_CertifiedCoverCriterion.np_subset_p_of_uniform_certified_cover

-- Approaches 56-58: set-level frontier
#print axioms PIsNPOrNot.ResearchAgenda.A56_SetLevelCollapse.p_eq_np_of_uniform_certified_cover
#print axioms PIsNPOrNot.ResearchAgenda.A57_ExactCriterion.p_eq_np_iff_uniform_poly_deciders
#print axioms PIsNPOrNot.ResearchAgenda.A58_ObstructionLocalization.exists_np_without_poly_decider_of_ne

-- Approaches 59-68: concrete SAT reductions and accounting
#print axioms PIsNPOrNot.ResearchFifth.A59_SeparatorConditioning.separator_exists
#print axioms PIsNPOrNot.ResearchFifth.A63_DavisPutnam.eliminate_one_variable
#print axioms PIsNPOrNot.ResearchFifth.A65_BoundedEliminationSchedule.work_le_length_mul_square
#print axioms PIsNPOrNot.ResearchFifth.A66_ThreeBudgetComposition.total_cost_polynomial
#print axioms PIsNPOrNot.ResearchFifth.A67_CostObstruction.expensive_leaf_of_total_exceeds
#print axioms PIsNPOrNot.ResearchFifth.A68_LogarithmicInterface.enumeration_times_polynomial

-- Approaches 69-75: private-variable peeling and cores
#print axioms PIsNPOrNot.ResearchSixth.A69_PrivateVariable.eliminate_private_variable
#print axioms PIsNPOrNot.ResearchSixth.A70_XorLeaf.xor3_solvable_for_first
#print axioms PIsNPOrNot.ResearchSixth.A72_PeelChain.PeelChain.correct
#print axioms PIsNPOrNot.ResearchSixth.A73_CoreLocalization.original_iff_core
#print axioms PIsNPOrNot.ResearchSixth.A74_SmallCoreBudget.total_cost_bound
#print axioms PIsNPOrNot.ResearchSixth.A75_CoreObstruction.expensive_core_of_total_exceeds

-- Approaches 76-90: proof-carrying AND/OR DAGs
#print axioms PIsNPOrNot.ResearchSeventh.A77_LocalValidity.eval_correct
#print axioms PIsNPOrNot.ResearchSeventh.A87_LayeredWidth.layeredNodes_le_length_mul
#print axioms PIsNPOrNot.ResearchSeventh.A88_WidthDepthBudget.width_depth_cost
#print axioms PIsNPOrNot.ResearchSeventh.A90_DagCollapseCriterion.np_subset_p_of_uniform_dag_cover

-- Approaches 91-105: concrete CNF proof trees
#print axioms PIsNPOrNot.ResearchEighth.A97_CNFShannon.sat_restrict_branch
#print axioms PIsNPOrNot.ResearchEighth.A100_DisjointDecomposition.sat_append_iff
#print axioms PIsNPOrNot.ResearchEighth.A102_CNFProofValidity.eval_correct
#print axioms PIsNPOrNot.ResearchEighth.A105_PolynomialCNFCertificate.Compiler.decide_correct

-- Approaches 106-120: minimal semantic residual states
#print axioms PIsNPOrNot.ResearchNinth.A109_StateCollisionSafety.same_state_equivalent
#print axioms PIsNPOrNot.ResearchNinth.A112_ResidualLowerBound.residual_image_card_le_state_card
#print axioms PIsNPOrNot.ResearchNinth.A113_CanonicalOptimality.canonical_image_eq
#print axioms PIsNPOrNot.ResearchNinth.A117_ResidualObstruction.state_space_exceeds_budget
#print axioms PIsNPOrNot.ResearchNinth.A120_ResidualCollapseCriterion.np_subset_p_of_uniform_residual_cover

-- Approaches 121-135: acceptable ordered-residual compiler skeleton
#print axioms PIsNPOrNot.ResearchTenth.A124_ExistentialDecision.decide_correct
#print axioms PIsNPOrNot.ResearchTenth.A125_LayerWidth.reachable_layer_bound
#print axioms PIsNPOrNot.ResearchTenth.A131_CompiledWorkBound.compiled_layer_work_bound
#print axioms PIsNPOrNot.ResearchTenth.A132_TotalCertifiedCost.total_cost_bound
#print axioms PIsNPOrNot.ResearchTenth.A134_CollapseCriterion.p_eq_np_of_uniform_compiler
#print axioms PIsNPOrNot.ResearchTenth.A135_CompilerObstruction.compiler_obstruction_of_separation


-- Approaches 136-150: adaptive residual branching
#print axioms PIsNPOrNot.ResearchEleventh.A139_AdaptiveShannon.residual_branch
#print axioms PIsNPOrNot.ResearchEleventh.A141_RankDecrease.rank_assign_lt
#print axioms PIsNPOrNot.ResearchEleventh.A143_AdaptiveValidity.eval_correct
#print axioms PIsNPOrNot.ResearchEleventh.A144_AdaptiveDepth.height_le_rank
#print axioms PIsNPOrNot.ResearchEleventh.A148_AdaptiveDagBudget.dagNodes_le_depth_mul_width
#print axioms PIsNPOrNot.ResearchEleventh.A149_AdaptiveCompiler.Compiler.decide_correct

-- Approaches 151-165: globally measured policy improvement
#print axioms PIsNPOrNot.ResearchTwelfth.A155_AdaptiveBaseline.adaptive_best_le_ordered
#print axioms PIsNPOrNot.ResearchTwelfth.A157_SharedUnion.union_inter_identity
#print axioms PIsNPOrNot.ResearchTwelfth.A159_StrictSharing.union_card_lt_sum_of_intersection
#print axioms PIsNPOrNot.ResearchTwelfth.A160_ImprovementChain.final_le_initial
#print axioms PIsNPOrNot.ResearchTwelfth.A163_PortfolioBaseline.choosePortfolio_cost_le_seed
#print axioms PIsNPOrNot.ResearchTwelfth.A165_PolicyCollapseCriterion.p_eq_np_of_uniform_policy_portfolios


-- Approaches 166-225: overlap, canonical states, coherent frontiers, and pruning
#print axioms PIsNPOrNot.ResearchThirteenth.A166_OverlapAccounting.union_plus_overlap
#print axioms PIsNPOrNot.ResearchThirteenth.A170_EqualSumComparison.union_nonincreasing_of_overlap
#print axioms PIsNPOrNot.ResearchThirteenth.A176_PolynomialPortfolioStates.portfolio_state_bound
#print axioms PIsNPOrNot.ResearchFourteenth.A181_CanonicalRepresentation.node_card_eq_state_card
#print axioms PIsNPOrNot.ResearchFourteenth.A185_ContextStrictSaving.new_total_card_lt_old_total
#print axioms PIsNPOrNot.ResearchFourteenth.A193_PolynomialStateToNode.node_bound_of_state_bound
#print axioms PIsNPOrNot.ResearchFifteenth.A199_ClosureUniqueness.reachable_unique
#print axioms PIsNPOrNot.ResearchFifteenth.A206_CoherentUnionClosure.union_closed
#print axioms PIsNPOrNot.ResearchFifteenth.A209_CoherentCompositionCost.composition_cost_identity
#print axioms PIsNPOrNot.ResearchSixteenth.A216_CompatibilityTransfer.compatible_of_dominates
#print axioms PIsNPOrNot.ResearchSixteenth.A221_SafePruning.prune_dominated
#print axioms PIsNPOrNot.ResearchSixteenth.A224_FrontierProductBudget.pair_count_bound
#print axioms PIsNPOrNot.ResearchSixteenth.A225_FrontierCollapseCriterion.p_eq_np_of_uniform_polynomial_frontiers


-- Approaches 226-330: radical representations, transformations, restrictions, and modular counting
#print axioms PIsNPOrNot.ResearchSeventeenth.A226_FeatureQuotient.exists_witness_iff_feature_image
#print axioms PIsNPOrNot.ResearchSeventeenth.A232_OrbitDecision.exists_witness_iff_representative_image
#print axioms PIsNPOrNot.ResearchSeventeenth.A240_RadicalCoverCriterion.p_eq_np_of_radical_cover
#print axioms PIsNPOrNot.ResearchEighteenth.A241_BijectiveTransform.exists_after_decode_iff
#print axioms PIsNPOrNot.ResearchEighteenth.A250_LinearSketchSafety.collision_safe
#print axioms PIsNPOrNot.ResearchEighteenth.A255_TransformSketchCollapse.p_eq_np_of_uniform_transform_sketch_cover
#print axioms PIsNPOrNot.ResearchNineteenth.A257_AllMaskFamilies.all_mask_family_card
#print axioms PIsNPOrNot.ResearchNineteenth.A261_ParityStateBound.parity_image_le_two
#print axioms PIsNPOrNot.ResearchNineteenth.A267_KnownParityCoordinate.parity_machine_exact
#print axioms PIsNPOrNot.ResearchNineteenth.A270_LinearBasisCollapse.p_eq_np_of_uniform_linear_sketches
#print axioms PIsNPOrNot.ResearchTwentieth.A273_StrictCanonicalCompression.canonical_image_card_lt
#print axioms PIsNPOrNot.ResearchTwentieth.A275_PermutationSearchSpace.permutation_family_card
#print axioms PIsNPOrNot.ResearchTwentieth.A281_ProductFeature.equal_product_feature_equal_answer
#print axioms PIsNPOrNot.ResearchTwentieth.A285_SymmetryLinearCollapse.p_eq_np_of_uniform_symmetry_linear_portfolio
#print axioms PIsNPOrNot.ResearchTwentyFirst.A286_RestrictionCover.sat_iff_some_restriction
#print axioms PIsNPOrNot.ResearchTwentyFirst.A287_ResidualSolverComposition.solve_some_iff_specification
#print axioms PIsNPOrNot.ResearchTwentyFirst.A294_CommonCoreAccounting.common_core_union_bound
#print axioms PIsNPOrNot.ResearchTwentyFirst.A300_RestrictionCollapse.p_eq_np_of_uniform_restriction_covers
#print axioms PIsNPOrNot.ResearchTwentySecond.A303_NetworkPreservesSAT.exists_decoded_iff
#print axioms PIsNPOrNot.ResearchTwentySecond.A309_MonotoneNetworkSearch.final_le_initial
#print axioms PIsNPOrNot.ResearchTwentySecond.A315_ReversibleCollapse.p_eq_np_of_uniform_reversible_compilers
#print axioms PIsNPOrNot.ResearchTwentyThird.A317_ZeroCountCriterion.accepted_count_eq_zero_iff
#print axioms PIsNPOrNot.ResearchTwentyThird.A323_ExactModularSAT.no_witness_iff_large_residue_zero
#print axioms PIsNPOrNot.ResearchTwentyThird.A329_ModularCompilerCriterion.compiler_decides_no_witness
#print axioms PIsNPOrNot.ResearchTwentyThird.A330_ModularCollapse.p_eq_np_of_uniform_modular_compilers


-- Approaches 331-390: learned reversible compilers and nonlinear feature covers
#print axioms PIsNPOrNot.ResearchTwentyFourth.A335_BeamBaseline.chosen_exact_and_bounded
#print axioms PIsNPOrNot.ResearchTwentyFourth.A336_GateNetworkCount.network_space_card
#print axioms PIsNPOrNot.ResearchTwentyFourth.A345_LearnedCollapse.p_eq_np_of_uniform_learned_compilers
#print axioms PIsNPOrNot.ResearchTwentyFifth.A348_SignatureImageDecision.exists_witness_iff_signature_image
#print axioms PIsNPOrNot.ResearchTwentyFifth.A349_SignatureCardinality.signature_image_le_pow_two
#print axioms PIsNPOrNot.ResearchTwentyFifth.A360_NonlinearCollapse.p_eq_np_of_uniform_nonlinear_observables
#print axioms PIsNPOrNot.ResearchTwentySixth.A364_SeparationImpliesFiberSafety.same_features_same_label
#print axioms PIsNPOrNot.ResearchTwentySixth.A373_BitPairBarrier.bit_pair_space_card
#print axioms PIsNPOrNot.ResearchTwentySixth.A375_FeatureCoverCollapse.p_eq_np_of_uniform_separating_features
#print axioms PIsNPOrNot.ResearchTwentySeventh.A379_FeatureImageTransport.pullback_image_eq
#print axioms PIsNPOrNot.ResearchTwentySeventh.A386_SeparationPullback.transformed_cover_gives_original_cover
#print axioms PIsNPOrNot.ResearchTwentySeventh.A390_CombinedCollapse.p_eq_np_of_uniform_transform_feature_compilers

-- Approaches 391-450: reachable-image generation, exact tables, and syndromes
#print axioms PIsNPOrNot.ResearchTwentyEighth.A398_OutputReachabilityCircularity.true_mem_output_image_iff
#print axioms PIsNPOrNot.ResearchTwentyEighth.A399_OutputOracleEquivalence.oracle_decides_existence
#print axioms PIsNPOrNot.ResearchTwentyEighth.A405_ReachabilityAwareCollapse.p_eq_np_of_uniform_reachable_quotients
#print axioms PIsNPOrNot.ResearchTwentyNinth.A407_ProductImage.reachable_product_eq
#print axioms PIsNPOrNot.ResearchTwentyNinth.A413_SeparatorImageExact.allBuckets_eq_global_image
#print axioms PIsNPOrNot.ResearchTwentyNinth.A420_StructuralImageCollapse.p_eq_np_of_uniform_structural_image_generators
#print axioms PIsNPOrNot.ResearchThirtieth.A421_ExactImageTable.rows_eq_reachableImage
#print axioms PIsNPOrNot.ResearchThirtieth.A432_OutputTableCircularity.true_mem_output_table_iff
#print axioms PIsNPOrNot.ResearchThirtieth.A435_StructuralPlanCollapse.p_eq_np_of_uniform_structural_plans
#print axioms PIsNPOrNot.ResearchThirtyFirst.A437_SyndromeImageExact.reachable_eq_coordinate_image
#print axioms PIsNPOrNot.ResearchThirtyFirst.A438_SyndromeCardinality.reachable_card_le_pow_two
#print axioms PIsNPOrNot.ResearchThirtyFirst.A448_OutputSyndromeCircularity.true_coordinate_gives_witness
#print axioms PIsNPOrNot.ResearchThirtyFirst.A450_SyndromeCollapse.p_eq_np_of_uniform_syndrome_compilers

-- Approaches 451-525: exact circuit messages, read-once formulas, and internal cutsets
#print axioms PIsNPOrNot.ResearchThirtySecond.A454_JoinMessage.joinMessage
#print axioms PIsNPOrNot.ResearchThirtySecond.A456_HideSeparator.hideSeparator
#print axioms PIsNPOrNot.ResearchThirtySecond.A462_HiddenSeparatorWidth.hidden_card_le
#print axioms PIsNPOrNot.ResearchThirtyThird.A469_PossibleOutputsExact.possible_exact
#print axioms PIsNPOrNot.ResearchThirtyThird.A474_ReadOnceSolver.solve_correct
#print axioms PIsNPOrNot.ResearchThirtyThird.A475_ReconvergenceCounterexample.no_shared_witness
#print axioms PIsNPOrNot.ResearchThirtyFourth.A484_BinaryGateRows.mem_rows
#print axioms PIsNPOrNot.ResearchThirtyFourth.A490_EliminationMaterialization.total_rows_le_steps_mul
#print axioms PIsNPOrNot.ResearchThirtyFifth.A497_CutsetUnionExact.allImages_eq_reachable
#print axioms PIsNPOrNot.ResearchThirtyFifth.A505_CertifiedCutset.decide_correct
#print axioms PIsNPOrNot.ResearchThirtySixth.A513_SubstitutedImageUnion.image_eq_branch_union
#print axioms PIsNPOrNot.ResearchThirtySixth.A517_ArbitraryWireConditioning.exists_transport
#print axioms PIsNPOrNot.ResearchThirtySixth.A522_BaselineSafeCutsetChoice.chosen_work_le_baseline
#print axioms PIsNPOrNot.ResearchThirtySixth.A525_InternalCutsetCollapse.p_eq_np_of_uniform_internal_cutsets

-- Approaches 526-585: exact residual quotients, safe certificates, and semantic optimality
#print axioms PIsNPOrNot.ResearchThirtySeventh.A529_SignatureImageSafety.equal_reachable_images
#print axioms PIsNPOrNot.ResearchThirtySeventh.A534_RepresentativeExistence.exists_over_representatives
#print axioms PIsNPOrNot.ResearchThirtySeventh.A535_RepresentativeImageUnion.representative_outputs_exact
#print axioms PIsNPOrNot.ResearchThirtySeventh.A540_SemanticQuotientCollapse.p_eq_np_of_uniform_semantic_quotients
#print axioms PIsNPOrNot.ResearchThirtyEighth.A542_CertificateToSignature.equal_signature
#print axioms PIsNPOrNot.ResearchThirtyEighth.A550_ExpressionCertificate.system
#print axioms PIsNPOrNot.ResearchThirtyEighth.A555_CertificateCollapse.p_eq_np_of_uniform_safe_certificates
#print axioms PIsNPOrNot.ResearchThirtyNinth.A562_LayerWidthBound.total_states_le_depth_mul_width
#print axioms PIsNPOrNot.ResearchThirtyNinth.A563_RawPathBarrier.binary_paths
#print axioms PIsNPOrNot.ResearchThirtyNinth.A570_RecursiveQuotientCollapse.p_eq_np_of_uniform_recursive_quotients
#print axioms PIsNPOrNot.ResearchFortieth.A572_SignatureImageFactorization.signatures_eq_decoded_certificates
#print axioms PIsNPOrNot.ResearchFortieth.A573_SemanticOptimalityBound.semantic_card_le_certificate_card
#print axioms PIsNPOrNot.ResearchFortieth.A580_CollisionSaving.strict_collision_saving
#print axioms PIsNPOrNot.ResearchFortieth.A585_ResidualKernelCollapse.p_eq_np_of_uniform_residual_kernels
